Activa Windows 11
slmgr /ipk TX9XD-98N7V-6WMQ6-BX7FG-H8Q99
slmgr /skms kms.digiboy.ir 
slmgr /ato

REM Windows 11 Home: TX9XD-98N7V-6WMQ6-BX7FG-H8Q99
REM Windows 11 Home Single Lenguage: 7HNRX-D7KGG-3K4RQ-4WPJ4-YTDFH 
REM Windows 11 Professional: W269N-WFGWX-YVC9B-4J6C9-T83GX
REM Windows 11 Professional N: MH37W-N47XK-V7XM9-C7227-GCQG9
REM Windows 11 Education: NW6C2-QMPVW-D7KKK-3GKT6-VCFB2
REM Windows 11 Education N: 2WH4N-8QGBV-H22JP-CT43Q-MDWWJ
REM Windows 11 Workstations: NRG8B-VKK3Q-CXVCJ-9G2XF-6Q84J
REM Windows 11 Pro for Workstations N: 9FNHH-K3HBT-3W4TD-6383H-6XYWF